// Embed docs + CLI into a TS module so route handlers never touch the filesystem
// (keeps Vercel function bundles small and avoids file-tracing surprises).
import fs from "node:fs";
const files = { "AGENTS.md": "docs/AGENTS.md", "SKILL.md": "docs/SKILL.md", "llms.txt": "docs/llms.txt", wb: "cli/wb.mjs" };
const out = Object.entries(files).map(([k, p]) => `  ${JSON.stringify(k)}: ${JSON.stringify(fs.readFileSync(p, "utf8"))},`).join("\n");
fs.writeFileSync("lib/generated-docs.ts", `// GENERATED by scripts/embed-docs.mjs. Edit docs/ and cli/ instead.\nexport const DOCS: Record<string, string> = {\n${out}\n};\n`);
console.log("embedded", Object.keys(files).join(", "));
