// Embed docs + CLIs into a TS module so route handlers never touch the filesystem
// (keeps Vercel function bundles small and avoids file-tracing surprises).
import fs from "node:fs";
const files = { "AGENTS.md": "docs/AGENTS.md", "SKILL.md": "docs/SKILL.md", "llms.txt": "docs/llms.txt", wb: "cli/wb.mjs", "wb.py": "cli/wb.py", "install.sh": "cli/install.sh" };
const src = Object.fromEntries(Object.entries(files).map(([k, p]) => [k, fs.readFileSync(p, "utf8")]));
// Both CLI flavors speak the same protocol: their versions must match.
const vNode = /const VERSION = "(\d+\.\d+\.\d+)"/.exec(src.wb)?.[1];
const vPy = /^VERSION = "(\d+\.\d+\.\d+)"/m.exec(src["wb.py"])?.[1];
if (!vNode || vNode !== vPy) { console.error(`embed-docs: CLI versions differ (node ${vNode}, python ${vPy}). Bump both.`); process.exit(1); }
const out = Object.entries(src).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
fs.writeFileSync("lib/generated-docs.ts", `// GENERATED by scripts/embed-docs.mjs. Edit docs/ and cli/ instead.\nexport const DOCS: Record<string, string> = {\n${out}\n};\n`);
console.log("embedded", Object.keys(files).join(", "), `(wb ${vNode})`);
